import { StyleSheet, Platform } from "react-native";

export const CARD_RADIUS = 28;
export const ACCENT = "#003366";
export const PLACEHOLDER_COLOR = "#E8EAED";

export const locationInformationStyle = StyleSheet.create({
    card: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: "#fff",
        borderTopLeftRadius: CARD_RADIUS,
        borderTopRightRadius: CARD_RADIUS,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.14,
        shadowRadius: 24,
        elevation: 24,
        zIndex: 100,
        maxHeight: "75%",
        overflow: "hidden",
    },

    // ── Image header
    imageContainer: {
        height: 190,
        width: "100%",
        overflow: "hidden",
        borderTopLeftRadius: CARD_RADIUS,
        borderTopRightRadius: CARD_RADIUS,
        backgroundColor: PLACEHOLDER_COLOR,
    },
    image: {
        width: "100%",
        height: "100%",
    },
    imagePlaceholder: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        gap: 8,
        backgroundColor: "#F8F9FA",
    },
    imagePlaceholderIconWrap: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: "#F1F3F4",
        justifyContent: "center",
        alignItems: "center",
    },
    imagePlaceholderLabel: {
        fontSize: 12,
        color: "#9AA0A6",
    },
    imageGradient: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        height: 80,
        justifyContent: "flex-end",
    },
    imageGradientInner: {
        height: 80,
        backgroundColor: "rgba(0,0,0,0.48)",
        opacity: 0.85,
    },
    closeBtn: {
        position: "absolute",
        top: 14,
        right: 14,
    },
    closeBtnInner: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: "rgba(255,255,255,0.92)",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 4,
    },
    categoryBadge: {
        position: "absolute",
        top: 14,
        left: 14,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    categoryLabel: {
        fontSize: 11,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    imageNameOverlay: {
        position: "absolute",
        bottom: 12,
        left: 16,
        right: 60,
    },
    imageNameText: {
        fontSize: 20,
        fontWeight: "800",
        color: "#fff",
        letterSpacing: -0.3,
        textShadowColor: "rgba(0,0,0,0.4)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 4,
    },

    // ── Content
    content: {
        paddingHorizontal: 20,
        flexGrow: 0,
    },
    handleBar: {
        width: 36,
        height: 4,
        backgroundColor: "#E0E0E0",
        borderRadius: 2,
        alignSelf: "center",
        marginVertical: 12,
    },
    locationName: {
        fontSize: 20,
        fontWeight: "800",
        color: "#202124",
        letterSpacing: -0.3,
        marginBottom: 10,
    },
    metaRow: {
        flexDirection: "row",
        gap: 8,
        flexWrap: "wrap",
        marginBottom: 10,
    },
    metaChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: "#F1F3F4",
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    metaChipText: {
        fontSize: 12,
        color: "#5F6368",
        fontWeight: "500",
    },
    description: {
        fontSize: 14,
        color: "#5F6368",
        lineHeight: 21,
        marginBottom: 14,
    },
    infoSection: {
        backgroundColor: "#F8F9FA",
        borderRadius: 16,
        padding: 14,
        gap: 10,
        marginBottom: 16,
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    infoIcon: {
        width: 28,
        height: 28,
        borderRadius: 10,
        backgroundColor: "#EAF1FB",
        justifyContent: "center",
        alignItems: "center",
    },
    infoText: {
        fontSize: 13,
        color: "#5F6368",
        flex: 1,
    },

    // ── Footer
    footer: {
        flexDirection: "row",
        gap: 12,
        paddingHorizontal: 20,
        paddingTop: 4,
        paddingBottom: Platform.OS === "ios" ? 36 : 24,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "#F1F3F4",
    },
    navigateBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        backgroundColor: ACCENT,
        paddingVertical: 14,
        borderRadius: 24,
        shadowColor: ACCENT,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 6,
    },
    navigateBtnText: {
        color: "#fff",
        fontSize: 15,
        fontWeight: "700",
        letterSpacing: 0.2,
    },
    shareBtn: {
        width: 52,
        height: 52,
        borderRadius: 26,
        borderWidth: 1.5,
        borderColor: "rgba(26,115,232,0.2)",
        backgroundColor: "#EAF1FB",
        justifyContent: "center",
        alignItems: "center",
    },
    cuposRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    cuposBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: "#E8F5E9",
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    cuposBadgeText: {
        fontSize: 12,
        color: "#34A853",
        fontWeight: "600",
    },
    cuposEmpty: {
        backgroundColor: "#FDEEEC",
    },
    cuposEmptyText: {
        color: "#EA4335",
    },
});