import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '85%',
        height: '85%',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    closeButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#202124',
    },
    scrollView: {
        flex: 1,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyText: {
        marginTop: 16,
        fontSize: 16,
        color: '#999',
    },
    avatarSection: {
        alignItems: 'center',
        paddingVertical: 24,
        backgroundColor: '#F8F9FA',
    },
    avatarCircle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#E8F0FE',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#4285F4',
    },
    section: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    personName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#202124',
        textAlign: 'center',
        marginBottom: 8,
    },
    cargoTag: {
        alignSelf: 'center',
        backgroundColor: '#E8F0FE',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 16,
        marginBottom: 8,
    },
    cargoText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4285F4',
    },
    employeeNumber: {
        fontSize: 14,
        color: '#5F6368',
        textAlign: 'center',
        marginTop: 4,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#202124',
        marginLeft: 8,
    },
    infoText: {
        fontSize: 15,
        color: '#5F6368',
        lineHeight: 22,
        marginLeft: 28,
    },
    contactItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        marginLeft: 28,
    },
    contactText: {
        fontSize: 15,
        color: '#4285F4',
        marginLeft: 12,
    },
    actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 20,
        paddingVertical: 20,
        gap: 12,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4285F4',
        paddingVertical: 16,
        borderRadius: 12,
        gap: 4,
    },
    actionButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#fff',
    },
    coordinatesSection: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#F8F9FA',
        marginBottom: 20,
    },
    coordinatesLabel: {
        fontSize: 12,
        color: '#5F6368',
        marginBottom: 4,
    },
    coordinatesText: {
        fontSize: 11,
        color: '#80868B',
        fontFamily: 'monospace',
    },
});