import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F2F2F2",
    },
    header: {
        height: 140,
        backgroundColor: "#1D356B",
        paddingHorizontal: 20,
        paddingTop: 50,
        alignItems: "flex-end",
        justifyContent: "flex-start",
    },
    headerLogo: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    headerLogoText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
        letterSpacing: 0.4,
    },
    headerLogoSubText: {
        color: "#9CC3FF",
        fontSize: 12,
        fontWeight: "600",
    },
    content: {
        backgroundColor: "#fff",
        marginTop: -10,
        marginHorizontal: 16,
        borderRadius: 16,
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 24,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 5,
    },
    avatarWrapper: {
        position: "absolute",
        top: -42,
        alignItems: "center",
        justifyContent: "center",
    },
    avatar: {
        width: 92,
        height: 92,
        borderRadius: 46,
        borderWidth: 4,
        borderColor: "#fff",
    },
    editAvatarButton: {
        position: "absolute",
        right: -6,
        bottom: -2,
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: "#fff",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 3,
    },
    name: {
        marginTop: 8,
        fontSize: 20,
        fontWeight: "700",
        color: "#111",
    },
    badge: {
        marginTop: 8,
        borderWidth: 1,
        borderColor: "#333",
        paddingHorizontal: 14,
        paddingVertical: 4,
        borderRadius: 14,
    },
    badgeText: {
        fontSize: 12,
        fontWeight: "600",
        color: "#222",
    },
    email: {
        marginTop: 16,
        fontSize: 13,
        color: "#777",
    },
    infoList: {
        marginTop: 24,
        width: "100%",
        gap: 10,
    },
    infoItem: {
        fontSize: 14,
        color: "#333",
    },
    logoutButton: {
        marginTop: 24,
        backgroundColor: "#8B0F1A",
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 8,
        minWidth: 200,
        alignItems: "center",
    },
    logoutButtonText: {
        color: "#fff",
        fontSize: 15,
        fontWeight: "600",
    },
    bottomNav: {
        position: "absolute",
        left: 12,
        right: 12,
        bottom: 40,
        backgroundColor: "#fff",
        borderRadius: 999,
        paddingVertical: 10,
        paddingHorizontal: 16,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 6,
    },
    navItem: {
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        minWidth: 64,
    },
    navLabel: {
        fontSize: 12,
        color: "#555",
        fontWeight: "600",
    },
});

export default styles;
